### ISSUE TITLE
BDD tests do _not_ report exceptions when _creating_ `HapiSpec`s

### ISSUE THREAD

**Issue by david-bakin-sl** [hiero-ledger/hiero-consensus-node#6912]
### Description

The BDD suite, in order to get tests to run, calls "factory" methods that return `HapiSpec`s which are the test to run.

If the _factory method throw an exception_ it is _not_ reported in the CI run and _none_ of the tests in that suite are run, with no notice to user.

Consider `bdd.suites.autorenew.MacroFeesChargedSanityCheckSuite`, which is instantiated by `EndToEndPackageRunner`.  Take a look at [line 90](https://github.com/hashgraph/hedera-services/blob/9a81b5eb77427aa0a0697f63973c69db88c7d536/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/MacroFeesChargedSanityCheckSuite.java#L90) or [line 144](https://github.com/hashgraph/hedera-services/blob/9a81b5eb77427aa0a0697f63973c69db88c7d536/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/MacroFeesChargedSanityCheckSuite.java#L144).  These lines call the [`ExtantCryptoContext` builders](https://github.com/hashgraph/hedera-services/blob/9a81b5eb77427aa0a0697f63973c69db88c7d536/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/crypto/ExtantCryptoContext.java#L105).  According to [the condition tested here](https://github.com/hashgraph/hedera-services/blob/9a81b5eb77427aa0a0697f63973c69db88c7d536/hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/crypto/ExtantCryptoContext.java#L140) they need to provide _9 field_ initializers to the builder - but they don't - they only provide 5.  So the builder throws an exception, and the _entire test suite doesn't run_.  In CI the exception is eaten somewhere and _no notice appears in any log_.

Apparently between the time the test was written, and now, more fields were added to the `ExtantCryptoContext` and the test has been failing to run ever since but nobody noticed.

(If you run the test locally you see the following:

```
> Task :hedera-node:test-clients:MacroFeesChargedSanityCheckSuite.main() FAILED
2023-06-02 16:22:03.666 INFO   232  MacroFeesChargedSanityCheckSuite - -------------- STARTING MacroFeesChargedSanityCheck SUITE --------------
Exception in thread "main" java.lang.IllegalStateException: Field mask is 31, not 511!
	at com.hedera.node.app.hapi.fees.usage.crypto.ExtantCryptoContext$Builder.build(ExtantCryptoContext.java:142)
	at com.hedera.services.bdd.suites.autorenew.MacroFeesChargedSanityCheckSuite.feesChargedMatchNumberOfRenewals(MacroFeesChargedSanityCheckSuite.java:152)
	at com.hedera.services.bdd.suites.autorenew.MacroFeesChargedSanityCheckSuite.getSpecsInSuite(MacroFeesChargedSanityCheckSuite.java:74)
	at com.hedera.services.bdd.suites.HapiSuite.runSuite(HapiSuite.java:235)
	at com.hedera.services.bdd.suites.HapiSuite.runSuiteSync(HapiSuite.java:222)
	at com.hedera.services.bdd.suites.autorenew.MacroFeesChargedSanityCheckSuite.main(MacroFeesChargedSanityCheckSuite.java:68)

Execution failed for task ':hedera-node:test-clients:MacroFeesChargedSanityCheckSuite.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

There are other suites which fail to initialize on my machine:
- `bdd.suites.schedule.ScheduleExecutionSpecs`
- `bdd.suites.perf.contract.opcodes.SStoreOperationLoadTest`
- `bdd.suites.schedule.ScheduleLongTermExecutionSpecs`

And these are only the ones I've checked so far.

The itest/e2e test runners should be fixed to report all errors and exceptions in the CI environment so that suites which aren't run are made known as failures.

- See related #6814 for more of them.  
- See also #6914 for more detailed analysis of multiple problems with `ContractPerformanceSuite`.
- See also #6915 for more detailed analysis of `MacroFeesChargedSanityCheck`.
- See also #6916 for moving some utility functions that deal with adjusting resource paths.

### Steps to reproduce

1. Go to the suite in IntelliJ, run the suite by clicking on the right-pointing-green-arrow next to the suite class declaration, see that it reports an exception.
1. Go to any CI run for any merged PR and see that that suite doesn't show up at all as reporting an error or otherwise.

### Hedera network

other

### Version

`develop` on 2023-06-02

### Operating system

macOS

**Comment by david-bakin-sl** [comment]
Correction:  What actually happens is that when a suite generates multiple tests - most of them do - the test that threw the exception _and all following ones_ in the list at `getSpecsInSuite` are skipped.

**Comment by david-bakin-sl** [comment]
Been awhile, need to repro again.

**Comment by Ferparishuertas** [comment]
Closing based on that it seems outdated
