### ISSUE TITLE
BDD Suite `MacroFeesChargedSanityCheckSuite` fails to run because the builder is incomplete

### ISSUE THREAD

**Issue by david-bakin-sl** [hiero-ledger/hiero-consensus-node#6915]
### Description

BDD Suite `MacroFeesChargedSanityCheckSuite` fails to run any tests because it throws an exception when trying to create the `HapiSpecs`.  Two tests try to build a `ExtantCryptoContext` with `ExtantCryptoContext.newBuilder()` but throw exceptions because that builder _requires_ every field to be supplied to it.  But the two tests are missing some fields:

- `setCurrentMaxAutomatiAssocations`
- `setCurrentCryptoAllowances`
- `setCurrentTokenAllowances`
- `setCurrentApproveForAllNftAllowances`

(I tried to fix this by adding the following code to each builder expression

```
              .setCurrentMaxAutomaticAssociations(10)
              .setCurrentCryptoAllowances(Collections.emptyMap())
              .setCurrentTokenAllowances(Collections.emptyMap())
              .setCurrentApproveForAllNftAllowances(Collections.emptySet())```

but though the tests initialized (didn't throw an exception) they FAILED.  So maybe non-empty collections of some sort need to be passed in, or the test needs to be corrected in some other way.

### Steps to reproduce

1. Go to `MacroFeesChargedSanityCheckSuite.java` in IntelliJ
1. Click on the green arrow next to `public class MacroFeesChargedSanityCheckSuite ...`
1. Click on the "run" menu item
1. See the following output instead of a successful run:
```
> Task :hedera-node:test-clients:MacroFeesChargedSanityCheckSuite.main() FAILED
2023-06-03 15:22:49.693 INFO   232  MacroFeesChargedSanityCheckSuite - -------------- STARTING MacroFeesChargedSanityCheck SUITE --------------
Exception in thread "main" java.lang.IllegalStateException: Field mask is 31, not 511!
	at com.hedera.node.app.hapi.fees.usage.crypto.ExtantCryptoContext$Builder.build(ExtantCryptoContext.java:142)
	at com.hedera.services.bdd.suites.autorenew.MacroFeesChargedSanityCheckSuite.feesChargedMatchNumberOfRenewals(MacroFeesChargedSanityCheckSuite.java:152)
	at com.hedera.services.bdd.suites.autorenew.MacroFeesChargedSanityCheckSuite.getSpecsInSuite(MacroFeesChargedSanityCheckSuite.java:74)
	at com.hedera.services.bdd.suites.HapiSuite.runSuite(HapiSuite.java:235)
	at com.hedera.services.bdd.suites.HapiSuite.runSuiteSync(HapiSuite.java:222)
	at com.hedera.services.bdd.suites.autorenew.MacroFeesChargedSanityCheckSuite.main(MacroFeesChargedSanityCheckSuite.java:68)

Execution failed for task ':hedera-node:test-clients:MacroFeesChargedSanityCheckSuite.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1```

### Additional context

See also #6912 which reports that suites which fail to initialize - e.g., by throwing an exception from `HapiSuite.getSpecsInSuite()` fail silently: no message at all to user.

### Hedera network

other

### Version

`develop` as of 2023-06-03

### Operating system

Other

**Comment by david-bakin-sl** [comment]
Been awhile, need to repro again.

**Comment by Ferparishuertas** [comment]
Seems outdated
